# Generated by Django 3.1.3 on 2021-01-04 02:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('landing_page', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('live_site', models.URLField()),
                ('repo_link', models.URLField()),
            ],
        ),
    ]
